apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-auth
  template:
    metadata:
      labels:
        app: flask-auth
    spec:
      containers:
        - name: flask-auth-container
          image: your-dockerhub/flask-auth-app:latest
          ports:
            - containerPort: 5000
            imagePullPolicy: Never
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: flask-auth-service
spec:
  selector:
    app: flask-auth
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080